### ISSUE TITLE
Time to populate the wobsite

### ISSUE THREAD

**Issue by kuklinistvan** [ankicommunity/ankicommunity.github.io#1]
(wobsite is not a misspelling, it is one of my annoying references to https://xkcd.com/148/)

> I think we need a separate ticket for that, because that would be a bigger project. If we are to populate that page, It would be great if it point to our Gitter channel, have some rudimentary news feed, and of course, would have a tutorial section.
> 
> Are you familiar with MKDocs? It has a gorgeous Material Design theme with an awesome search module and it is almost ridiculous how easy it is to use.
> Guys, check it out, we can easily host it from Github Pages.
> 
> https://squidfunk.github.io/mkdocs-material/getting-started/
> https://www.mkdocs.org/user-guide/deploying-your-docs/

**Comment by kuklinistvan** [comment]
MkDocs Material theme


![image](https://user-images.githubusercontent.com/19473224/95659247-02470580-0b20-11eb-965d-256b25d4a17f.png)
![image](https://user-images.githubusercontent.com/19473224/95659253-125ee500-0b20-11eb-9a47-0cafe2b56b35.png)

It's also responsive

![image](https://user-images.githubusercontent.com/19473224/95659264-1f7bd400-0b20-11eb-82b7-8286bcbc6e4a.png)

**Comment by nathmo** [comment]
it support markdown so it should be okay (i dont really see the constraint involved so it's hard to tell if there are any drawbacks) 
for me it look really good and since it's markdown behind it should be easy to use.

**Comment by kuklinistvan** [comment]
Yes, I used it before and it was super easy :) I also think that the result is very inviting for beginners.

**Comment by nathmo** [comment]
so to make sure they aren't any misunderstanding.
this website will be the wiki for the whole anki community set of projects ?
each projects should link there in the readme

**Comment by kuklinistvan** [comment]
Yes, each project, news, tutorials, getting involved, Gitter, our favorite cat videos (just kidding), etc.

**Comment by nathmo** [comment]
ring me when MkDocs  is ready ^^

**Comment by kuklinistvan** [comment]
I'm really sorry, right now I'm working on university stuff - but it should not be hard to get going. I'm trying to catch up with the news from the community, though.

https://squidfunk.github.io/mkdocs-material/getting-started/

**Comment by kuklinistvan** [comment]
But wait a second...

**Comment by kuklinistvan** [comment]
@VikashKothary, @AntonOfTheWoods can you give me permission to the repository to test the website?
https://github.com/ankicommunity/ankicommunity.github.io

**Comment by kuklinistvan** [comment]
![image](https://user-images.githubusercontent.com/19473224/95659725-48ea2f00-0b23-11eb-9b73-753b48561fe9.png)

**Comment by kuklinistvan** [comment]
![image](https://user-images.githubusercontent.com/19473224/95660001-38d34f00-0b25-11eb-89be-5b04292ace2b.png)

```
# Creating a Docker image

To create a Docker image, you need to do that.

\```
./some_file.sh
\```

???+ "Summary"
    Here's some content.
```

(the codeblock is escaped)

**Comment by nathmo** [comment]
nice, i will find a bit of motivation an try to make a better PR

**Comment by VikashKothary** [comment]
@kuklinistvan I'm giving you access to this repo but we aware we already have a mkdocs here: https://github.com/ankicommunity/anki-sync-server/tree/develop/docs which pushes to https://anki-sync-server.readthedocs.io/. 

Although I do like the idea of an organisation-wide wiki. So let's see where this goes.

EDIT: I think I've given you permission to be able to set it up but let me know if you've got any issues. I'm still getting familiar with the access-control rules.

**Comment by kuklinistvan** [comment]
Uploaded the initial version
